<?php

use Illuminate\Database\Seeder;

class OrderDetailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0');
        \Illuminate\Support\Facades\DB::table('order_details')->truncate();
        \Illuminate\Support\Facades\DB::table('order_details')->insert([
            [
                'orderId'=>1,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1000000
            ],
            [
                'orderId'=>2,
                'productId'=>3,
                'quantity'=>1,
                'unitPrice'=>1000000
            ],
            [
                'orderId'=>3,
                'productId'=>5,
                'quantity'=>1,
                'unitPrice'=>200000
            ],
            [
                'orderId'=>4,
                'productId'=>6,
                'quantity'=>1,
                'unitPrice'=>1000000
            ],
            [
                'orderId'=>5,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1000000
            ],
            [
                'orderId'=>6,
                'productId'=>3,
                'quantity'=>1,
                'unitPrice'=>1000000
            ],
            [
                'orderId'=>7,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1000000
            ],
            [
                'orderId'=>8,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1000000
            ],
            [
                'orderId'=>9,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1300000
            ],
            [
                'orderId'=>10,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>2500000
            ],
            [
                'orderId'=>11,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>4500000
            ],
            [
                'orderId'=>12,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1230000
            ],
            [
                'orderId'=>13,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1640000
            ],
            [
                'orderId'=>14,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1560000
            ],
            [
                'orderId'=>15,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1450000
            ],
            [
                'orderId'=>16,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1050000
            ],
            [
                'orderId'=>17,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>3000000
            ],
            [
                'orderId'=>18,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1040000
            ],
            [
                'orderId'=>19,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1070000
            ],
            [
                'orderId'=>20,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1000000
            ],
            [
                'orderId'=>21,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>800000
            ],
            [
                'orderId'=>22,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1100000
            ],
            [
                'orderId'=>23,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1400000
            ],
            [
                'orderId'=>24,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1090000
            ],
            [
                'orderId'=>25,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1050000
            ],
            [
                'orderId'=>26,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1006000
            ],
            [
                'orderId'=>27,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>2700000
            ],
            [
                'orderId'=>28,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>1900000
            ],
            [
                'orderId'=>29,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>890000
            ],
            [
                'orderId'=>30,
                'productId'=>2,
                'quantity'=>1,
                'unitPrice'=>790000
            ],
        ]);
    }
}
