<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'id' => 1,
                'name'=>'Hoa hồng',
                'price'=>40000,
                'categoryId'=>1,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng.',
                'sale' => 0,
                'detail' => 'Hoa hồng đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'name'=>'Hoa hồng đỏ',
                'price'=>40000,
                'categoryId'=>1,
                'collectionId' =>2,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ đẹp.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'name'=>'Hoa hồng đỏ tình yêu',
                'price'=>120000,
                'categoryId'=>1,
                'collectionId' =>3,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>1,
                'collectionId' =>4,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Lãng hoa hồng.',
                'sale' => 0,
                'detail' => 'Lãng hoa hồng đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'name'=>'Lãng hoa hồng phai',
                'price'=>100000,
                'categoryId'=>1,
                'collectionId' =>4,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>2,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>2,
                'collectionId' =>2,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'name'=>'Lãng hoa hồng tươi',
                'price'=>100000,
                'categoryId'=> 2,
                'collectionId' =>3,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'name'=>'Hồng cánh sen',
                'price'=>100000,
                'categoryId'=>2,
                'collectionId' =>4,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>2,
                'collectionId' =>4,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 16,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>2,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'http://res.cloudinary.com/dug9zryzq/image/upload/v1535334937/1535334909.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
