<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'id' => 1,
                'name'=>'Hoa hồng',
                'price'=>40000,
                'categoryId'=>1,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/gio-hoa-chuc-mung-dua-ua-chuong-nhat735.jpg',
                'description'=>'Hoa hồng.',
                'sale' => 10,
                'detail' => 'Hoa hồng đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'name'=>'Hoa hồng đỏ',
                'price'=>40000,
                'categoryId'=>1,
                'collectionId' =>2,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hoa-hong-tim-dep-nhat653.jpg',
                'description'=>'Hoa hồng đỏ đẹp.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'name'=>'Hoa hồng đỏ tình yêu',
                'price'=>120000,
                'categoryId'=>1,
                'collectionId' =>3,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/vong-hoa-dam-tang953.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>1,
                'collectionId' =>4,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/hoa-bo-dep-nu-cuoi-tho-ngay731.jpg',
                'description'=>'Lãng hoa hồng.',
                'sale' => 5,
                'detail' => 'Lãng hoa hồng đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'name'=>'Lãng hoa hồng phai',
                'price'=>100000,
                'categoryId'=>1,
                'collectionId' =>4,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/lang-hoa-dep-hoa-chuc-mung574.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>2,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/hoa-bo-dep-tinh-trong-tim592.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 2,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>2,
                'collectionId' =>2,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/dieu-gian-di527.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'name'=>'Lãng hoa hồng tươi',
                'price'=>100000,
                'categoryId'=> 2,
                'collectionId' =>3,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hoa-loa-ken-dep-nhat859.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 6,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'name'=>'Hồng cánh sen',
                'price'=>100000,
                'categoryId'=>2,
                'collectionId' =>4,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hoa-sinh-nhat-loi-yeu-thuong172.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>2,
                'collectionId' =>4,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/hoa-bo-tang-sep189.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/hoa-mau-don-trang-quoc-sac-thien-huong296.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hoa-huong-duong-duoc-ua-chuong-nhat100.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/hoa-bo-dep-nu-cuoi-tho-ngay731.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hoa-vi-em-la-chinh-em213.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 15,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hoa-tuoi-dep-co-nhau-tron-doi175.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 16,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hoa-yeu-xa275.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hong-xanh-dep-nhat357.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/bo-hoa-noi-ket-yeu-thuong450.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>2,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/luc-moi-yeu747.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 4,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'name'=>'Lãng hoa hồng',
                'price'=>100000,
                'categoryId'=>3,
                'collectionId' =>1,
                'images'=>'https://hoatuoi360.vn/upload/hinhanh/thumb/em-la-so-mot428.jpg',
                'description'=>'Hoa hồng đỏ tình yêu.',
                'sale' => 0,
                'detail' => 'Hoa hồng đỏ tình yêu đẹp lắm đấy.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
